spring.application.name=song-organizer
spring.datasource.url=jdbc:postgresql://localhost:5438/music_organizer
spring.flyway.default-schema=organizer_schema
spring.datasource.username=postgres
spring.datasource.password=postgres
server.port=8089
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
cloudinary.api-secret=kEwvr_Z7XAkLzQ5DpjV6dsDjY4Y
cloudinary.api-key=377879647913618
cloudinary.cloud-name=dj5f5e5cx
jwt.secret=8639400922:AAFvoJsSDM5IFeRewLM2LkFytL1FScBPk9g